// Generated by gencpp from file sensor_synchronizer/SyncDataMsg.msg
// DO NOT EDIT!


#ifndef SENSOR_SYNCHRONIZER_MESSAGE_SYNCDATAMSG_H
#define SENSOR_SYNCHRONIZER_MESSAGE_SYNCDATAMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <sensor_msgs/Image.h>
#include <sensor_msgs/Image.h>

namespace sensor_synchronizer
{
template <class ContainerAllocator>
struct SyncDataMsg_
{
  typedef SyncDataMsg_<ContainerAllocator> Type;

  SyncDataMsg_()
    : header()
    , image_left()
    , image_right()
    , range_distance(0.0)
    , rtk_matrix_rotm()
    , rtk_matrix_euler()
    , rtk_latitude(0.0)
    , rtk_longitude(0.0)  {
    }
  SyncDataMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , image_left(_alloc)
    , image_right(_alloc)
    , range_distance(0.0)
    , rtk_matrix_rotm(_alloc)
    , rtk_matrix_euler(_alloc)
    , rtk_latitude(0.0)
    , rtk_longitude(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _image_left_type;
  _image_left_type image_left;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _image_right_type;
  _image_right_type image_right;

   typedef double _range_distance_type;
  _range_distance_type range_distance;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _rtk_matrix_rotm_type;
  _rtk_matrix_rotm_type rtk_matrix_rotm;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _rtk_matrix_euler_type;
  _rtk_matrix_euler_type rtk_matrix_euler;

   typedef double _rtk_latitude_type;
  _rtk_latitude_type rtk_latitude;

   typedef double _rtk_longitude_type;
  _rtk_longitude_type rtk_longitude;




  typedef boost::shared_ptr< ::sensor_synchronizer::SyncDataMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensor_synchronizer::SyncDataMsg_<ContainerAllocator> const> ConstPtr;

}; // struct SyncDataMsg_

typedef ::sensor_synchronizer::SyncDataMsg_<std::allocator<void> > SyncDataMsg;

typedef boost::shared_ptr< ::sensor_synchronizer::SyncDataMsg > SyncDataMsgPtr;
typedef boost::shared_ptr< ::sensor_synchronizer::SyncDataMsg const> SyncDataMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensor_synchronizer::SyncDataMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensor_synchronizer::SyncDataMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sensor_synchronizer

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'sensor_synchronizer': ['/home/yhlee/Sensor_Sync/src/sensor_synchronizer/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sensor_synchronizer::SyncDataMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_synchronizer::SyncDataMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_synchronizer::SyncDataMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_synchronizer::SyncDataMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_synchronizer::SyncDataMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_synchronizer::SyncDataMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensor_synchronizer::SyncDataMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bb36a0519783c0150aa9338d8c91d61c";
  }

  static const char* value(const ::sensor_synchronizer::SyncDataMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbb36a0519783c015ULL;
  static const uint64_t static_value2 = 0x0aa9338d8c91d61cULL;
};

template<class ContainerAllocator>
struct DataType< ::sensor_synchronizer::SyncDataMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_synchronizer/SyncDataMsg";
  }

  static const char* value(const ::sensor_synchronizer::SyncDataMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensor_synchronizer::SyncDataMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
sensor_msgs/Image image_left\n\
sensor_msgs/Image image_right\n\
float64 range_distance\n\
float64[] rtk_matrix_rotm\n\
float64[] rtk_matrix_euler\n\
float64 rtk_latitude\n\
float64 rtk_longitude\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: sensor_msgs/Image\n\
# This message contains an uncompressed image\n\
# (0, 0) is at top-left corner of image\n\
#\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of cameara\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
                     # If the frame_id here and the frame_id of the CameraInfo\n\
                     # message associated with the image conflict\n\
                     # the behavior is undefined\n\
\n\
uint32 height         # image height, that is, number of rows\n\
uint32 width          # image width, that is, number of columns\n\
\n\
# The legal values for encoding are in file src/image_encodings.cpp\n\
# If you want to standardize a new string format, join\n\
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n\
\n\
string encoding       # Encoding of pixels -- channel meaning, ordering, size\n\
                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n\
\n\
uint8 is_bigendian    # is this data bigendian?\n\
uint32 step           # Full row length in bytes\n\
uint8[] data          # actual matrix data, size is (step * rows)\n\
";
  }

  static const char* value(const ::sensor_synchronizer::SyncDataMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensor_synchronizer::SyncDataMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.image_left);
      stream.next(m.image_right);
      stream.next(m.range_distance);
      stream.next(m.rtk_matrix_rotm);
      stream.next(m.rtk_matrix_euler);
      stream.next(m.rtk_latitude);
      stream.next(m.rtk_longitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SyncDataMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensor_synchronizer::SyncDataMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensor_synchronizer::SyncDataMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "image_left: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.image_left);
    s << indent << "image_right: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.image_right);
    s << indent << "range_distance: ";
    Printer<double>::stream(s, indent + "  ", v.range_distance);
    s << indent << "rtk_matrix_rotm[]" << std::endl;
    for (size_t i = 0; i < v.rtk_matrix_rotm.size(); ++i)
    {
      s << indent << "  rtk_matrix_rotm[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.rtk_matrix_rotm[i]);
    }
    s << indent << "rtk_matrix_euler[]" << std::endl;
    for (size_t i = 0; i < v.rtk_matrix_euler.size(); ++i)
    {
      s << indent << "  rtk_matrix_euler[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.rtk_matrix_euler[i]);
    }
    s << indent << "rtk_latitude: ";
    Printer<double>::stream(s, indent + "  ", v.rtk_latitude);
    s << indent << "rtk_longitude: ";
    Printer<double>::stream(s, indent + "  ", v.rtk_longitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSOR_SYNCHRONIZER_MESSAGE_SYNCDATAMSG_H
