// Generated by gencpp from file snowmower_msgs/ObstacleMsg.msg
// DO NOT EDIT!


#ifndef SNOWMOWER_MSGS_MESSAGE_OBSTACLEMSG_H
#define SNOWMOWER_MSGS_MESSAGE_OBSTACLEMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace snowmower_msgs
{
template <class ContainerAllocator>
struct ObstacleMsg_
{
  typedef ObstacleMsg_<ContainerAllocator> Type;

  ObstacleMsg_()
    : angle(0.0)
    , distance(0.0)  {
    }
  ObstacleMsg_(const ContainerAllocator& _alloc)
    : angle(0.0)
    , distance(0.0)  {
  (void)_alloc;
    }



   typedef double _angle_type;
  _angle_type angle;

   typedef double _distance_type;
  _distance_type distance;




  typedef boost::shared_ptr< ::snowmower_msgs::ObstacleMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::snowmower_msgs::ObstacleMsg_<ContainerAllocator> const> ConstPtr;

}; // struct ObstacleMsg_

typedef ::snowmower_msgs::ObstacleMsg_<std::allocator<void> > ObstacleMsg;

typedef boost::shared_ptr< ::snowmower_msgs::ObstacleMsg > ObstacleMsgPtr;
typedef boost::shared_ptr< ::snowmower_msgs::ObstacleMsg const> ObstacleMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::snowmower_msgs::ObstacleMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::snowmower_msgs::ObstacleMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace snowmower_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'snowmower_msgs': ['/home/yhlee/Sensor_Sync/src/snowmower_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::snowmower_msgs::ObstacleMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::snowmower_msgs::ObstacleMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::snowmower_msgs::ObstacleMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::snowmower_msgs::ObstacleMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::snowmower_msgs::ObstacleMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::snowmower_msgs::ObstacleMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::snowmower_msgs::ObstacleMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f5a2ee2aaf541b354d2c44aa9ea8522e";
  }

  static const char* value(const ::snowmower_msgs::ObstacleMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf5a2ee2aaf541b35ULL;
  static const uint64_t static_value2 = 0x4d2c44aa9ea8522eULL;
};

template<class ContainerAllocator>
struct DataType< ::snowmower_msgs::ObstacleMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "snowmower_msgs/ObstacleMsg";
  }

  static const char* value(const ::snowmower_msgs::ObstacleMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::snowmower_msgs::ObstacleMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 angle\n\
float64 distance\n\
";
  }

  static const char* value(const ::snowmower_msgs::ObstacleMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::snowmower_msgs::ObstacleMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObstacleMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::snowmower_msgs::ObstacleMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::snowmower_msgs::ObstacleMsg_<ContainerAllocator>& v)
  {
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SNOWMOWER_MSGS_MESSAGE_OBSTACLEMSG_H
